//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int bill_id { get; set; }
        public int pat_id { get; set; }
        public decimal doctor_charge { get; set; }
        public decimal med_charge { get; set; }
        public Nullable<decimal> room_charge { get; set; }
        public Nullable<int> no_of_days { get; set; }
        public decimal total_bill { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
